@host = https://localhost:7162

### Crear una nueva orden
POST {{host}}/api/v1/orders
Content-Type: {{contentType}}

{
  "customerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "items": [
    {
      "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quantity": 2
    }
  ]
}

###

@orderId = {{createOrder.response.body.$.id}}

### Obtener una orden por ID
GET {{host}}/api/v1/orders/{{orderId}}

###

### Cancelar una orden
DELETE {{host}}/api/v1/orders/{{orderId}}